const translations: Record<string, Record<string, string>> = {
  Hindi: {
    'Dashboard': 'डैशबोर्ड',
    'My Profile': 'मेरी प्रोफ़ाइल',
    'Attendance': 'उपस्थिति',
    'Leave Requests': 'छुट्टी के अनुरोध',
    'Payslips': 'पेस्लिप्स',
    'Settings': 'सेटिंग्स',
    'Log Out': 'लॉग आउट',
    'Employees': 'कर्मचारी',
    'Finance': 'वित्त',
    'Accounts': 'खाते',
    'Invoices': 'चालान',
    'Payments': 'भुगतान',
    'HR & Payroll': 'एचआर और पेरोल',
    'Supply Chain': 'आपूर्ति श्रृंखला',
    'Inventory / Products': 'इन्वेंटरी / उत्पाद',
    'Vendors': 'विक्रेता',
    'Purchase Orders': 'क्रय आदेश',
    'Projects': 'परियोजनाएं',
    'Tasks': 'कार्य',
    'Resource Allocation': 'संसाधन आवंटन',
    'Reports': 'रिपोर्ट',
    'Financial Reports': 'वित्तीय रिपोर्ट',
    'Employee Reports': 'कर्मचारी रिपोर्ट',
    'Inventory Reports': 'इन्वेंटरी रिपोर्ट',
    'AI Insights': 'एआई अंतर्दृष्टि',
    'Welcome to ERP Portal': 'ईआरपी पोर्टल में आपका स्वागत है',
    'Amdox Technologies': 'एमडॉक्स टेक्नोलॉजीज',
    'User Dossier & Profile': 'उपयोगकर्ता डोजियर और प्रोफाइल',
    'HR & Payroll Management': 'एचआर और पेरोल प्रबंधन',
    'Project & Task Board': 'परियोजना और कार्य बोर्ड',
    'Inventory & Supply Chain': 'इन्वेंटरी और आपूर्ति श्रृंखला',
    'Finance Ledger & Accounts': 'वित्त बhi और खाते',
    'Enterprise Analytics & Reports': 'उद्यम विश्लेषिकी और रिपोर्ट'
  },
  Spanish: {
    'Dashboard': 'Tablero',
    'My Profile': 'Mi Perfil',
    'Attendance': 'Asistencia',
    'Leave Requests': 'Solicitudes de Permiso',
    'Payslips': 'Nóminas',
    'Settings': 'Configuración',
    'Log Out': 'Cerrar Sesión',
    'Employees': 'Empleados',
    'Finance': 'Finanzas',
    'Accounts': 'Cuentas',
    'Invoices': 'Facturas',
    'Payments': 'Pagos',
    'HR & Payroll': 'RRHH y Nómina',
    'Supply Chain': 'Cadena de Suministro',
    'Inventory / Products': 'Inventario / Productos',
    'Vendors': 'Proveedores',
    'Purchase Orders': 'Órdenes de Compra',
    'Projects': 'Proyectos',
    'Tasks': 'Tareas',
    'Resource Allocation': 'Asignación de Recursos',
    'Reports': 'Informes',
    'Financial Reports': 'Informes Financieros',
    'Employee Reports': 'Informes de Empleados',
    'Inventory Reports': 'Informes de Inventario',
    'AI Insights': 'Información de IA',
    'Welcome to ERP Portal': 'Bienvenido al Portal ERP',
    'Amdox Technologies': 'Tecnologías Amdox',
    'User Dossier & Profile': 'Dossier y Perfil de Usuario',
    'HR & Payroll Management': 'Gestión de RRHH y Nóminas',
    'Project & Task Board': 'Tablero de Proyectos y Tareas',
    'Inventory & Supply Chain': 'Inventario y Cadena de Suministro',
    'Finance Ledger & Accounts': 'Libro Mayor y Cuentas',
    'Enterprise Analytics & Reports': 'Análisis e Informes de Empresa'
  },
  French: {
    'Dashboard': 'Tableau de Bord',
    'My Profile': 'Mon Profil',
    'Attendance': 'Présence',
    'Leave Requests': 'Demandes de Congé',
    'Payslips': 'Fiches de Paie',
    'Settings': 'Paramètres',
    'Log Out': 'Se Déconnecter',
    'Employees': 'Employés',
    'Finance': 'Finances',
    'Accounts': 'Comptes',
    'Invoices': 'Factures',
    'Payments': 'Paiements',
    'HR & Payroll': 'RH & Paie',
    'Supply Chain': 'Chaîne Logistique',
    'Inventory / Products': 'Inventaire / Produits',
    'Vendors': 'Fournisseurs',
    'Purchase Orders': 'Bons de Commande',
    'Projects': 'Projets',
    'Tasks': 'Tâches',
    'Resource Allocation': 'Allocation des Ressources',
    'Reports': 'Rapports',
    'Financial Reports': 'Rapports Financiers',
    'Employee Reports': 'Rapports des Employés',
    'Inventory Reports': 'Rapports d\'Inventaire',
    'AI Insights': 'Analyses IA',
    'Welcome to ERP Portal': 'Bienvenue sur le Portail ERP',
    'Amdox Technologies': 'Technologies Amdox',
    'User Dossier & Profile': 'Dossier & Profil Utilisateur',
    'HR & Payroll Management': 'Gestion RH & Paie',
    'Project & Task Board': 'Tableau des Projets & Tâches',
    'Inventory & Supply Chain': 'Inventaire & Chaîne Logistique',
    'Finance Ledger & Accounts': 'Grand Livre & Comptes',
    'Enterprise Analytics & Reports': 'Analyses & Rapports d\'Entreprise'
  },
  German: {
    'Dashboard': 'Dashboard',
    'My Profile': 'Mein Profil',
    'Attendance': 'Anwesenheit',
    'Leave Requests': 'Urlaubsanträge',
    'Payslips': 'Gehaltsabrechnungen',
    'Settings': 'Einstellungen',
    'Log Out': 'Abmelden',
    'Employees': 'Mitarbeiter',
    'Finance': 'Finanzen',
    'Accounts': 'Konten',
    'Invoices': 'Rechnungen',
    'Payments': 'Zahlungen',
    'HR & Payroll': 'Personal & Gehalt',
    'Supply Chain': 'Lieferkette',
    'Inventory / Products': 'Inventar / Produkte',
    'Vendors': 'Lieferanten',
    'Purchase Orders': 'Bestellungen',
    'Projects': 'Projekte',
    'Tasks': 'Aufgaben',
    'Resource Allocation': 'Ressourcenzuweisung',
    'Reports': 'Berichte',
    'Financial Reports': 'Finanzberichte',
    'Employee Reports': 'Mitarbeiterberichte',
    'Inventory Reports': 'Inventarberichte',
    'AI Insights': 'KI-Einblicke',
    'Welcome to ERP Portal': 'Willkommen im ERP-Portal',
    'Amdox Technologies': 'Amdox Technologien',
    'User Dossier & Profile': 'Benutzerdossier & Profil',
    'HR & Payroll Management': 'Personal- & Gehaltsverwaltung',
    'Project & Task Board': 'Projekt- & Aufgabenboard',
    'Inventory & Supply Chain': 'Inventar & Lieferkette',
    'Finance Ledger & Accounts': 'Finanzbuchhaltung & Konten',
    'Enterprise Analytics & Reports': 'Unternehmensanalysen & Berichte'
  }
};

export const translate = (text: string): string => {
  if (typeof window === 'undefined') return text;
  const lang = localStorage.getItem('erp_language') || 'English';
  if (lang === 'English') return text;
  return translations[lang]?.[text] || text;
};
